const questions = [
    {
      id: 1,
      question: 'What is your refinancing goal today?',
      type: 'radio',
      options: [
        'Get out of debt faster',
        'Lower my monthly payments',
        'I am not sure',
      ],
      step: 1,
      visibility: true,
      values: 1,
      required: true,
    },
    {
      id: 2,
      question:
        'Please list all of your private student loans, including how much you currently owe, the interest rate and your minimum monthly payment (e.g., $10,000 at a 7% interest rate, with a monthly payment of $200)',
      type: 'listLoan',
      options: [],
      step: 2,
      visibility: true,
      values: 3,
      required: true,
    },
    {
      id: 3,
      question:
        'What\'s the most you would be able to pay towards your student loans each month?',
      type: 'number',
      options: [],
      step: 3,
      visibility: true,
      values: 1,
      required: true,
      placeholder: 'e.g., $250/month',
    },
    {
      id: 4,
      question: 'What school did you go to for undergraduate?',
      type: 'autofill',
      options: [],
      step: 4,
      visibility: true,
      placeholder: 'College',
      values: 1,
      required: true,
    },
    {
      id: 5,
      question:
        'What was your degree (e.g., Bachelor of Arts, Bachelor of Science, Bachelor of Fine Arts, etc.)?',
      type: 'autofill',
      options: [],
      step: 4,
      visibility: true,
      values: 1,
      required: true,
    },
    {
      id: 6,
      question: 'What was your major?',
      type: 'textbox',
      options: [],
      step: 4,
      visibility: true,
      values: 1,
      required: true,
    },
    {
      id: 7,
      question: 'Did you graduate?',
      type: 'boolean',
      options: ['Yes', 'No'],
      step: 4,
      subQuestion: {
        id: 1,
        yes: 'When did you graduate?',
        no: 'When was your last day of attendance?',
      },
      visibility: true,
      values: 1,
      required: true,
    },
    {
      id: 8,
      question: 'When did you graduate?',
      type: 'date',
      options: [],
      step: 4,
      visibility: false,
      values: 1,
      required: false,
    },
    {
      id: 9,
      question: 'When was your last day of attendance?',
      type: 'date',
      options: [],
      step: 4,
      visibility: false,
      values: 1,
      required: false,
    },
    {
      id: 10,
      question: 'Did you go to graduate school?',
      type: 'boolean',
      options: ['Yes', 'No'],
      step: 5,
      subQuestion: [
        'What school did you go to for graduate school?',
        'What was your degree?',
      ],
      visibility: true,
      values: 1,
      required: true,
    },
    {
      id: 11,
      question: 'What school did you go to for graduate school?',
      type: 'autofill',
      options: [],
      step: 5,
      visibility: false,
      placeholder: 'School',
      values: 1,
      required: false,
    },
    {
      id: 12,
      question: 'What was your degree?',
      type: 'textbox',
      options: [],
      step: 5,
      visibility: false,
      values: 1,
      required: false,
    },
    {
      id: 13,
      question: 'Tell us about your current employment',
      type: 'radio',
      options: [
        'I\'m a W2 employee (salaried or hourly)',
        'I\'m a 1099 independent contractor',
        'I\'m self-employed',
        'I\'m retired',
        'I\'m unemployed',
      ],
      step: 6,
      visibility: true,
      values: 1,
      required: true,
    },
    {
      id: 14,
      question: 'Are you employed in healthcare?',
      type: 'boolean',
      options: ['Yes', 'No'],
      step: 6,
      visibility: true,
      values: 1,
      required: true,
    },
    {
      id: 15,
      question: 'What is your employer\'s name?',
      type: 'textbox',
      options: [],
      step: 6,
      visibility: true,
      values: 1,
      required: true,
    },
    {
      id: 16,
      question: 'What industry are you in?',
      type: 'autofill',
      options: [],
      step: 6,
      visibility: true,
      placeholder: 'Industry',
      values: 1,
      required: true,
    },
    {
      id: 17,
      question: 'What is your official job title?',
      type: 'textbox',
      options: [],
      step: 6,
      visibility: true,
      values: 1,
      required: true,
    },
    {
      id: 18,
      question: 'When did you start working at your current employer?',
      type: 'date',
      options: [],
      step: 6,
      visibility: true,
      values: 1,
      required: true,
    },
    {
      id: 19,
      question: 'What\'s your annual income?',
      type: 'number',
      options: [],
      step: 6,
      visibility: true,
      values: 1,
      required: true,
      placeholder: 'e.g., $75,000/year'
    },
    {
      id: 20,
      question: ' Please list any additional income sources',
      type: 'income',
      options: [],
      step: 7,
      visibility: true,
      values: 2,
      required: true,
    },
    {
      id: 21,
      question:
        'How much money do you have in savings or investments? Enter any cash you have in checking/savings accounts, retirement funds, or other investments',
      type: 'number',
      options: [],
      step: 7,
      visibility: true,
      placeholder: 'e.g., $50,000',
      values: 1,
      required: true,
    },
    {
      id: 22,
      question: ' What is your permanent address? ',
      type: 'address',
      options: [],
      step: 8,
      visibility: true,
      values: 4,
      required: true,
    },
    {
      id: 23,
      question: 'What\'s your current living situation?',
      type: 'radio2',
      options: [
        'I\'m renting',
        'I own with a mortgage',
        'I own without a mortgage',
        'I don\'t pay for housing (e.g., I live with relatives)',
      ],
      step: 8,
      visibility: true,
      values: 1,
      required: true,
    },
    {
      id: 24,
      question: 'What\'s your monthly housing payment?',
      type: 'number',
      options: [],
      step: 8,
      visibility: true,
      values: 1,
      required: true,
      placeholder: 'e.g., $2,000/month',
    },
    {
      id: 25,
      question: 'What\'s your citizenship status?',
      type: 'radio',
      options: [
        'U.S. Citizen',
        'Permanent Resident/Green Card Holder',
        'Visa Holder',
      ],
      step: 8,
      visibility: true,
      values: 1,
      required: true,
    },
    {
      id: 26,
      question:
        'Last step! What\'s your Social Security Number? To check your rates, we\'ll need to do a soft credit check. Checking your rate WILL NOT affect your credit score.',
      type: 'number',
      options: [],
      smallText:
        '“By entering this information, you understand and agree that you are providing written consent to Sonny and related third-parties to obtain information from TransUnion and Experian for the purposes of providing you with refinancing options for which you pre-qualify. Sonny will not share, distribute or use your SSN for any purposes other than helping you refinance your student loan. This data is safely transmitted and stored through a secure connection”',
      step: 9,
      visibility: true,
      values: 1,
      required: true,
      placeholder: 'XXX-XXX-XXX'
    },
  ];
  module.exports = { questions };